/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Link = {
  label?: string;
  url?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & IntroBlock)
  | ({
      _key: string;
    } & NotesBlock)
>;

export type NotesBlock = {
  _type: "notesBlock";
  behavior?: string;
};

export type IntroBlock = {
  _type: "introBlock";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  eyebrow?: string;
  heading?: string;
  content?: BlockContent;
  link?: Link;
};

export type Notes = {
  _id: string;
  _type: "notes";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt?: string;
  body?: BlockContent;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Configuration = {
  _id: string;
  _type: "configuration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  homePage?: PageReference;
  footerMenu?: Array<
    {
      _key: string;
    } & PageReference
  >;
  socialShareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  body?: BlockContent;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Link
  | SanityImageAssetReference
  | BlockContent
  | NotesBlock
  | IntroBlock
  | Notes
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | PageReference
  | Configuration
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../frontend/src/app/(site)/[slug]/page.tsx
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    title,    slug,    body  }
export type PAGE_BY_SLUG_QUERY_RESULT = {
  title: string | null;
  slug: Slug | null;
  body: BlockContent | null;
} | null;

// Source: ../frontend/src/app/(site)/note/[slug]/page.tsx
// Variable: NOTE_BY_SLUG_QUERY
// Query: *[_type == "notes" && slug.current == $slug][0]{    _type,    title,    slug,    publishedAt,    mainImage,    body  }
export type NOTE_BY_SLUG_QUERY_RESULT = {
  _type: "notes";
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  body: BlockContent | null;
} | null;

// Source: ../frontend/src/app/(site)/page.tsx
// Variable: HOME_QUERY
// Query: *[_id == "configuration"][0]{  homePage->{    title,    slug,    body  }}
export type HOME_QUERY_RESULT =
  | {
      homePage: null;
    }
  | {
      homePage: {
        title: string | null;
        slug: Slug | null;
        body: BlockContent | null;
      } | null;
    }
  | null;

// Source: ../frontend/src/app/(site)/page.tsx
// Variable: NOTES_QUERY
// Query: *[_type == "notes" && defined(slug.current)] | order(publishedAt desc)[0...12]{    _id,    title,    slug,    publishedAt  }
export type NOTES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
}>;

// Source: ../frontend/src/app/layout.tsx
// Variable: SITE_CONFIG_QUERY
// Query: *[_id == "configuration"][0]{  footerMenu[]->{    _id,    title,    slug  },  socialShareImage{    asset,    alt,    hotspot,    crop  }}
export type SITE_CONFIG_QUERY_RESULT =
  | {
      footerMenu: null;
      socialShareImage: null;
    }
  | {
      footerMenu: Array<{
        _id: string;
        title: string | null;
        slug: Slug | null;
      }> | null;
      socialShareImage: {
        asset: SanityImageAssetReference | null;
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
    }
  | null;

// Source: ../frontend/src/sanity/portable-body.tsx
// Variable: NOTES_FOR_PORTABLE_BLOCK_QUERY
// Query: *[_type == "notes" && defined(slug.current)] | order(publishedAt desc) {    _id,    title,    slug,    publishedAt  }
export type NOTES_FOR_PORTABLE_BLOCK_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "page" && slug.current == $slug][0]{\n    title,\n    slug,\n    body\n  }': PAGE_BY_SLUG_QUERY_RESULT;
    '*[_type == "notes" && slug.current == $slug][0]{\n    _type,\n    title,\n    slug,\n    publishedAt,\n    mainImage,\n    body\n  }': NOTE_BY_SLUG_QUERY_RESULT;
    '*[_id == "configuration"][0]{\n  homePage->{\n    title,\n    slug,\n    body\n  }\n}': HOME_QUERY_RESULT;
    '*[_type == "notes" && defined(slug.current)] | order(publishedAt desc)[0...12]{\n    _id,\n    title,\n    slug,\n    publishedAt\n  }': NOTES_QUERY_RESULT;
    '*[_id == "configuration"][0]{\n  footerMenu[]->{\n    _id,\n    title,\n    slug\n  },\n  socialShareImage{\n    asset,\n    alt,\n    hotspot,\n    crop\n  }\n}': SITE_CONFIG_QUERY_RESULT;
    '*[_type == "notes" && defined(slug.current)] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    publishedAt\n  }': NOTES_FOR_PORTABLE_BLOCK_QUERY_RESULT;
  }
}
